s3_conf:
  s3_bucket: consumer-datamart
  staging_dir: stg

SRC:
  MYSQL:
    customer_test:
      dbtable: testdb.customer_test
      partition_column: CustomerID
      query : "(select * from testdb.customer_test ) as t"  
    individual_test:
      dbtable: testdb.individual_test
      partition_column: CustomerID
      query : "(select * from testdb.individual_test ) as t"  
    ccard:
      dbtable: testdb.ccard
      partition_column: CreditCardID
      query : "(select * from testdb.ccard ) as t"  
    store:
      dbtable: testdb.store
      partition_column: CustomerID
      query : "(select * from testdb.store ) as t"  
    salesterritory:
      dbtable: testdb.salesterritory
      partition_column: TerritoryID
      query : "(select * from testdb.salesterritory ) as t"  
    salesperson:
      dbtable: testdb.salesperson
      partition_column: SalesPersonID
      query : "(select * from testdb.salesperson ) as t"  
    salesorderheader:
      dbtable: testdb.salesorderheader
      partition_column: SalesOrderID
      query : "(select * from testdb.salesorderheader ) as t"  
    salesorderdetail:
      dbtable: testdb.salesorderdetail
      partition_column: SalesOrderID
      query : "(select * from testdb.salesorderdetail ) as t"  
    specialoffer:
      dbtable: testdb.specialoffer
      partition_column: SpecialOfferID
      query : "(select * from testdb.specialoffer ) as t"  

redshift_conf:
  dim:
    CUSTOMERDIM:
      srcQuery: select cus.CustomerID,
        cus.AccountNumber, 
        cus.CustomerType, 
        ind.Demographics, 
        cus.TerritoryID,
        cus.ModifiedDate,
        udfMD5withPython(array(
        cus.CustomerID,
        cus.AccountNumber, 
        cus.CustomerType, 
        ind.Demographics, 
        cus.TerritoryID,
        cus.ModifiedDate
        )
        ) AS UpdateKey from CUSTOMER cus join INDIVIDUAL ind on ind.CustomerID = cus.CustomerID 
      readDimDataQuery: select CustomerKey,
        CustomerID,
        AccountNumber, 
        CustomerType, 
        Demographics, 
        TerritoryID,
        ModifiedDate,
        updatekey 
        from CUSTOMERDIM
      updatesQuery: select CustomerDim.CustomerKey,
        CustomerStg.CustomerID,
        CustomerStg.AccountNumber, 
        CustomerStg.CustomerType, 
        CustomerStg.Demographics, 
        CustomerStg.TerritoryID,
        CustomerStg.ModifiedDate,
        CustomerStg.updatekey 
        from CustomerStg INNER 
        JOIN CustomerDim 
        ON CustomerStg.CustomerID = CustomerDim.CustomerID
        WHERE CustomerStg.UpdateKey <> CustomerDim.UpdateKey
      newQuery: select CustomerDim.*,
        from CustomerStg LEFT OUTER JOIN
        JOIN CustomerDim 
        ON CustomerStg.CustomerID = CustomerDim.CustomerID
        WHERE CustomerDim.CustomerID is null
      bulkUpdateQuery: update CustomerDim
        set CustomerStg.CustomerID = isnull(update.CustomerID,CustomerDim.CustomerID),
        CustomerStg.AccountNumber = isnull(update.AccountNumber,CustomerDim.AccountNumber),
        CustomerStg.CustomerType = isnull(update.CustomerType,CustomerDim.CustomerType),
        CustomerStg.Demographics = isnull(update.Demographics,CustomerDim.Demographics),
        CustomerStg.TerritoryID = isnull(update.TerritoryID,CustomerDim.TerritoryID),
        CustomerStg.ModifiedDate = isnull(update.ModifiedDate,CustomerDim.ModifiedDate),
        CustomerStg.updatekey = isnull(update.updatekey,CustomerDim.updatekey)
        from UPDATE_CUSTOMERDIM update
        where update.CustomerID=CustomerDim.CustomerID
        and update.updatekey <> CustomerDim.updatekey

# sftp_conf:
#     filetype: csv
#     delimiter: |
#     directory: /home/ubuntu/data

# mongodb_config:
#   database: school
#   collection: students